### PR TITLE
Format, lint, and new lint script

### PR DESCRIPTION
**Pull request by nguyenhuy0905**
# Format, lint and new linting script

- **What**:

Formatted all current source file. Update linting script to exclude build dir and include test dir. Also included 2 new GitHub actions, CMake multi-platform build and CodeQL.

- **Why**:

Format code so that it follows the format and linting options listed in .clang-format and .clang-tidy files.

I like the green tick effect when all GitHub actions run correctly :). To be fair, it isn't very useful for a project of this size.

- **How**:

I simply run formatting for all scripts, then go to each one and modify accordingly to the linter.

I added the GitHub action scripts, using the default provided by GitHub.

- **Tags**:

@qu-ngx @BAOELIETRAN @AbstractionHLR @bebeminhminh @aqt169

---

Pull request by: Huy Nguyen

### CODE REVIEW

**Comment by nguyenhuy0905** [comment]
Oh yea, I forgot that this was on pull-request and made some random pushes there.

**Comment by nguyenhuy0905** [comment]
Currently the check will fail when running MSVC though.

**Comment by nguyenhuy0905** [comment]
Nevermind, still failing.

**Comment by nguyenhuy0905** [comment]
But it should be fixed after this PR. I have another giant PR coming.

**Review by BAOELIETRAN — APPROVED** [review]
everything is gud

**Pull request merged**
