### PR TITLE
CMake linting and formatting

### PR DESCRIPTION
**Pull request by nguyenhuy0905**
# CMake linting and formatting

- **What**:

The include/smoldb file is deleted as a side effect to the gitignore. Sadly. But at least it's not a file we're using anyways.

- **Why**:

I hope you like writing CMake.

- **How**:

I run the command:

```bash
cmake-format --dump-config yaml > .cmake-format.yaml
```

- **Misc**:

Man I Love CMake (jk i dont)

---

Pull request by: Huy Nguyen

### CODE REVIEW

**Review by qu-ngx — APPROVED** [review]
SGTM enough for these CMake

Reviewer: Quang Nguyen

**Comment by nguyenhuy0905** [comment]
> SGTM enough for these CMake
> 
> Reviewer: Quang Nguyen

You know, I wish it was enough.

We are lacking a couple of things still, but the most important is unit testing. The other ones can be:

- install rules
- pack rules

But those, you can say, are for the later stages of the project when we're almost done with every basic functionalities.

**Review by qu-ngx — DISMISSED** [review]
LGTM! x2

Reviewer: Quang Nguyen

**Comment by nguyenhuy0905** [comment]
NOTE: you can dismiss this PR since #34 also includes this.

**Pull request closed without merging**
